select abs(-3.745) from dual;
select mod(16, 32) from dual;
-- select power(3, 4) from dual;
select round(-50.552, 2) from dual;
-- select trunc(50) from dual;
select sin(3) from dual;
select cos(17) from dual;
select tan(96) from dual;
select asin(0) from dual;
select acos(1) from dual;
select atan(50) from dual;
-- select sinh(51) from dual;
-- select cosh(51) from dual;
-- select tanh(51) from dual;
select sqrt(81) from dual;
select exp(1) from dual;
select ln(25) from dual;
select log(7, 14) from dual;
select ceil(20.722) from dual;
select floor(88.977) from dual;
-- select sing(7) from dual;